#+OPTIONS: hidestars
#+TITLE:FurAffinity Favorites downloader

This Perl script is designed to make it easy-peasy to download both your own
favorites, as well as the favorites of others.

* Requirements
Pretty much any version of modern Perl will work with this script. If 
you are on Linux or Mac OSX, you usually already have a version of Perl 
accessible to you and no installation is required on your part.

However, if you are on Windows, you will need to download a version of 
Perl for Windows. (I reccommend 
[[http://www.activestate.com/activeperl/downloads][ActivePerl]].)

When you install it, make sure that Perl is a part of your PATH.

* Usage
You can run this program from most command lines by simply typing its 
name when in the same folder as it (Or by specifying the place the 
script is at.).

- On Linux, you probably already know how to open the command line
- On Mac OSX, you can find your termial in Applications -> Utilities -> Terminal
- On Windows, you can type [Windows Key] + [R], type "cmd" and hit [Enter]

If you have literally no clue how to use this, the easiest way to 
download to a folder on any system is to drag the script to the terminal 
you have opened, add a space and "=-u=" followed by the user you want to 
download the favorites of, followed by another space, and then a "=-d=", 
then trag and drop the folder you want to download everything to onto 
the terminal.

The end result should look something like the following:
#+BEGIN_EXAMPLE
'/some/path/to/FAFD.pl' -u thingywhat -d '/some/path/to/your/download/folder'
#+END_EXAMPLE

When you have a line that looks similar (Not the exact same, yout paths 
will be different), hit [Enter] and watch the files download.

When you specify the "=-u=" option, all of the favorites of the user 
mentioned will be downloaded into a new folder called "downloads" in the 
current folder.

Also if you wish to specify a place for these files to be downloaded, 
you can specify so with the "=-d=" option.

For a largely abridged version of this help, if you invoke the script on 
its own, you'll see the following screen:

#+BEGIN_EXAMPLE
FurAffinity Favorites Downloader version 0.1
By thingywhat (https://github.com/thingywhat)

	-h			This help screen.
	-u <user> 		The user to work with. (Required)
	-d [folder]		Where to download the files.

	-v			Make downloads verbose.

For example, to download the favorites of thingywhat we could:

	./FAFD.pl -u thingywhat

Or to specify a palce for them to be downloaded:

	./FAFD.pl -u thingywhat -d ~/Downloads/FA
#+END_EXAMPLE
